spring.application.name=user-management

# postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/connectix
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin@123
# Ensure SQL initialization runs and runs after JPA schema creation
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Run on alternate port to avoid conflicts during development
server.port=8081

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Logging
logging.level.com.example.usermanagement=DEBUG

# JWT configuration
jwt.secret=gA#8pLm9!qZ2*vN4vY7@bX1&cW5%sK3j
jwt.expiration=86400000
