spring.application.name=user-management

# H2 Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/conectix
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=pwd
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Ensure SQL initialization runs and runs after JPA schema creation
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Run on alternate port to avoid conflicts during development
server.port=8081

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.com.example.usermanagement=DEBUG


